-- CreateEnum
CREATE TYPE "BankIssuer" AS ENUM ('BAC_CREDOMATIC', 'PROMERICA', 'NO_ISSUER');

-- CreateEnum
CREATE TYPE "BankCardType" AS ENUM ('AMEX_THE_PLATINUM_CARD', 'AMEX_CASHBACK_PREMIUM', 'AMEX_MILLAS_PLUS_BLACK', 'AMEX_PLATINUM', 'AMEX_INCAE', 'AMEX_AADVANTAGE_PRESTIGE', 'AMEX_LIFEMILES_ELITE', 'MASTERCARD_BLACK', 'MASTERCARD_PLATINUM', 'MASTERCARD_BLACK_MILLAS_PLUS', 'MASTERCARD_CASHBACK_PREMIUM', 'MASTERCARD_BLACK_AADVANTAGE', 'VISA_INFINITE', 'VISA_INFINITE_IBERIA', 'VISA_INFINITE_EMERALD', 'VISA_INFINITE_CONNECT_MILES', 'VISA_INFINITE_MILLAS_PLUS', 'VISA_PLATINO', 'LINCOLN_PLAZA', 'CORPORATE_BENEFICIARY', 'NO_CARD');

-- DropForeignKey
ALTER TABLE "Valet" DROP CONSTRAINT "Valet_companyId_fkey";

-- AlterTable
ALTER TABLE "TicketAssignment" ALTER COLUMN "role" DROP DEFAULT;

-- CreateTable
CREATE TABLE "BankCard" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "issuer" "BankIssuer" NOT NULL,
    "type" "BankCardType" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BankCard_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "BankCard_clientId_issuer_type_key" ON "BankCard"("clientId", "issuer", "type");

-- AddForeignKey
ALTER TABLE "BankCard" ADD CONSTRAINT "BankCard_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Valet" ADD CONSTRAINT "Valet_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
