export const COUNTRIES = [
  { code: "AF", label: "Afganistán" },
  { code: "AL", label: "Albania" },
  { code: "DE", label: "Alemania" },
  { code: "AD", label: "Andorra" },
  { code: "AO", label: "Angola" },
  { code: "AI", label: "Anguila" },
  { code: "AG", label: "Antigua y Barbuda" },
  { code: "SA", label: "Arabia Saudita" },
  { code: "DZ", label: "Argelia" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Armenia" },
  { code: "AW", label: "Aruba" },
  { code: "AU", label: "Australia" },
  { code: "AT", label: "Austria" },
  { code: "AZ", label: "Azerbaiyán" },
  { code: "BS", label: "Bahamas" },
  { code: "BH", label: "Baréin" },
  { code: "BD", label: "Bangladés" },
  { code: "BB", label: "Barbados" },
  { code: "BE", label: "Bélgica" },
  { code: "BZ", label: "Belice" },
  { code: "BJ", label: "Benín" },
  { code: "BM", label: "Bermudas" },
  { code: "BY", label: "Bielorrusia" },
  { code: "BO", label: "Bolivia" },
  { code: "BA", label: "Bosnia y Herzegovina" },
  { code: "BW", label: "Botsuana" },
  { code: "BR", label: "Brasil" },
  { code: "BN", label: "Brunéi" },
  { code: "BG", label: "Bulgaria" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "BT", label: "Bután" },
  { code: "CV", label: "Cabo Verde" },
  { code: "KH", label: "Camboya" },
  { code: "CM", label: "Camerún" },
  { code: "CA", label: "Canadá" },
  { code: "QA", label: "Catar" },
  { code: "TD", label: "Chad" },
  { code: "CL", label: "Chile" },
  { code: "CN", label: "China" },
  { code: "CY", label: "Chipre" },
  { code: "VA", label: "Ciudad del Vaticano" },
  { code: "CO", label: "Colombia" },
  { code: "KM", label: "Comoras" },
  { code: "CG", label: "Congo" },
  { code: "CD", label: "Congo (R.D.)" },
  { code: "KP", label: "Corea del Norte" },
  { code: "KR", label: "Corea del Sur" },
  { code: "CR", label: "Costa Rica" },
  { code: "CI", label: "Costa de Marfil" },
  { code: "HR", label: "Croacia" },
  { code: "CU", label: "Cuba" },
  { code: "CW", label: "Curazao" },
  { code: "DK", label: "Dinamarca" },
  { code: "DM", label: "Dominica" },
  { code: "EC", label: "Ecuador" },
  { code: "EG", label: "Egipto" },
  { code: "SV", label: "El Salvador" },
  { code: "AE", label: "Emiratos Árabes Unidos" },
  { code: "ER", label: "Eritrea" },
  { code: "SK", label: "Eslovaquia" },
  { code: "SI", label: "Eslovenia" },
  { code: "ES", label: "España" },
  { code: "US", label: "Estados Unidos" },
  { code: "EE", label: "Estonia" },
  { code: "ET", label: "Etiopía" },
  { code: "PH", label: "Filipinas" },
  { code: "FI", label: "Finlandia" },
  { code: "FJ", label: "Fiyi" },
  { code: "FR", label: "Francia" },
  { code: "GA", label: "Gabón" },
  { code: "GM", label: "Gambia" },
  { code: "GE", label: "Georgia" },
  { code: "GH", label: "Ghana" },
  { code: "GI", label: "Gibraltar" },
  { code: "GD", label: "Granada" },
  { code: "GR", label: "Grecia" },
  { code: "GL", label: "Groenlandia" },
  { code: "GP", label: "Guadalupe" },
  { code: "GT", label: "Guatemala" },
  { code: "GN", label: "Guinea" },
  { code: "GW", label: "Guinea-Bisáu" },
  { code: "GQ", label: "Guinea Ecuatorial" },
  { code: "GY", label: "Guyana" },
  { code: "GF", label: "Guyana Francesa" },
  { code: "HT", label: "Haití" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "HU", label: "Hungría" },
  { code: "IN", label: "India" },
  { code: "ID", label: "Indonesia" },
  { code: "IQ", label: "Irak" },
  { code: "IR", label: "Irán" },
  { code: "IE", label: "Irlanda" },
  { code: "IS", label: "Islandia" },
  { code: "MH", label: "Islas Marshall" },
  { code: "SB", label: "Islas Salomón" },
  { code: "IL", label: "Israel" },
  { code: "IT", label: "Italia" },
  { code: "JM", label: "Jamaica" },
  { code: "JP", label: "Japón" },
  { code: "JO", label: "Jordania" },
  { code: "KZ", label: "Kazajistán" },
  { code: "KE", label: "Kenia" },
  { code: "KG", label: "Kirguistán" },
  { code: "KI", label: "Kiribati" },
  { code: "KW", label: "Kuwait" },
  { code: "LA", label: "Laos" },
  { code: "LS", label: "Lesoto" },
  { code: "LV", label: "Letonia" },
  { code: "LB", label: "Líbano" },
  { code: "LR", label: "Liberia" },
  { code: "LY", label: "Libia" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lituania" },
  { code: "LU", label: "Luxemburgo" },
  { code: "MO", label: "Macao" },
  { code: "MG", label: "Madagascar" },
  { code: "MY", label: "Malasia" },
  { code: "MW", label: "Malaui" },
  { code: "MV", label: "Maldivas" },
  { code: "ML", label: "Malí" },
  { code: "MT", label: "Malta" },
  { code: "MA", label: "Marruecos" },
  { code: "MQ", label: "Martinica" },
  { code: "MU", label: "Mauricio" },
  { code: "MR", label: "Mauritania" },
  { code: "MX", label: "México" },
  { code: "FM", label: "Micronesia" },
  { code: "MD", label: "Moldavia" },
  { code: "MC", label: "Mónaco" },
  { code: "MN", label: "Mongolia" },
  { code: "ME", label: "Montenegro" },
  { code: "MS", label: "Montserrat" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibia" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Níger" },
  { code: "NG", label: "Nigeria" },
  { code: "NO", label: "Noruega" },
  { code: "NZ", label: "Nueva Zelanda" },
  { code: "OM", label: "Omán" },
  { code: "NL", label: "Países Bajos" },
  { code: "PK", label: "Pakistán" },
  { code: "PW", label: "Palaos" },
  { code: "PA", label: "Panamá" },
  { code: "PG", label: "Papúa Nueva Guinea" },
  { code: "PY", label: "Paraguay" },
  { code: "PE", label: "Perú" },
  { code: "PL", label: "Polonia" },
  { code: "PT", label: "Portugal" },
  { code: "PR", label: "Puerto Rico" },
  { code: "GB", label: "Reino Unido" },
  { code: "CZ", label: "República Checa" },
  { code: "DO", label: "República Dominicana" },
  { code: "CF", label: "República Centroafricana" },
  { code: "RE", label: "Reunión" },
  { code: "RW", label: "Ruanda" },
  { code: "RO", label: "Rumanía" },
  { code: "RU", label: "Rusia" },
  { code: "WS", label: "Samoa" },
  { code: "KN", label: "San Cristóbal y Nieves" },
  { code: "SM", label: "San Marino" },
  { code: "VC", label: "San Vicente y las Granadinas" },
  { code: "SH", label: "Santa Elena" },
  { code: "LC", label: "Santa Lucía" },
  { code: "ST", label: "Santo Tomé y Príncipe" },
  { code: "SN", label: "Senegal" },
  { code: "RS", label: "Serbia" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leona" },
  { code: "SG", label: "Singapur" },
  { code: "SO", label: "Somalia" },
  { code: "LK", label: "Sri Lanka" },
  { code: "SZ", label: "Suazilandia" },
  { code: "ZA", label: "Sudáfrica" },
  { code: "SD", label: "Sudán" },
  { code: "SS", label: "Sudán del Sur" },
  { code: "SE", label: "Suecia" },
  { code: "CH", label: "Suiza" },
  { code: "SR", label: "Surinam" },
  { code: "TH", label: "Tailandia" },
  { code: "TW", label: "Taiwán" },
  { code: "TZ", label: "Tanzania" },
  { code: "TJ", label: "Tayikistán" },
  { code: "TL", label: "Timor Oriental" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad y Tobago" },
  { code: "TN", label: "Túnez" },
  { code: "TM", label: "Turkmenistán" },
  { code: "TR", label: "Turquía" },
  { code: "TV", label: "Tuvalu" },
  { code: "UA", label: "Ucrania" },
  { code: "UG", label: "Uganda" },
  { code: "UY", label: "Uruguay" },
  { code: "UZ", label: "Uzbekistán" },
  { code: "VU", label: "Vanuatu" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "YE", label: "Yemen" },
  { code: "DJ", label: "Yibuti" },
  { code: "ZM", label: "Zambia" },
  { code: "ZW", label: "Zimbabue" },
] as const;

export const CURRENCIES = [
  { code: "AED", label: "AED — Dírham de los EAU" },
  { code: "AFN", label: "AFN — Afgani afgano" },
  { code: "ALL", label: "ALL — Lek albanés" },
  { code: "AMD", label: "AMD — Dram armenio" },
  { code: "ANG", label: "ANG — Florín antillano" },
  { code: "AOA", label: "AOA — Kwanza angoleño" },
  { code: "ARS", label: "ARS — Peso argentino" },
  { code: "AUD", label: "AUD — Dólar australiano" },
  { code: "AWG", label: "AWG — Florín arubeño" },
  { code: "AZN", label: "AZN — Manat azerbaiyano" },
  { code: "BAM", label: "BAM — Marco bosnio-herzegovino" },
  { code: "BBD", label: "BBD — Dólar de Barbados" },
  { code: "BDT", label: "BDT — Taka bangladesí" },
  { code: "BGN", label: "BGN — Lev búlgaro" },
  { code: "BHD", label: "BHD — Dinar bareiní" },
  { code: "BIF", label: "BIF — Franco burundés" },
  { code: "BMD", label: "BMD — Dólar de Bermudas" },
  { code: "BND", label: "BND — Dólar de Brunéi" },
  { code: "BOB", label: "BOB — Boliviano" },
  { code: "BRL", label: "BRL — Real brasileño" },
  { code: "BSD", label: "BSD — Dólar de las Bahamas" },
  { code: "BTN", label: "BTN — Ngultrum butanés" },
  { code: "BWP", label: "BWP — Pula botsuanesa" },
  { code: "BYN", label: "BYN — Rublo bielorruso" },
  { code: "BZD", label: "BZD — Dólar de Belice" },
  { code: "CAD", label: "CAD — Dólar canadiense" },
  { code: "CDF", label: "CDF — Franco congoleño" },
  { code: "CHF", label: "CHF — Franco suizo" },
  { code: "CLP", label: "CLP — Peso chileno" },
  { code: "CNY", label: "CNY — Yuan chino" },
  { code: "COP", label: "COP — Peso colombiano" },
  { code: "CRC", label: "CRC — Colón costarricense" },
  { code: "CUP", label: "CUP — Peso cubano" },
  { code: "CVE", label: "CVE — Escudo caboverdiano" },
  { code: "CZK", label: "CZK — Corona checa" },
  { code: "DJF", label: "DJF — Franco yibutiano" },
  { code: "DKK", label: "DKK — Corona danesa" },
  { code: "DOP", label: "DOP — Peso dominicano" },
  { code: "DZD", label: "DZD — Dinar argelino" },
  { code: "EGP", label: "EGP — Libra egipcia" },
  { code: "ERN", label: "ERN — Nakfa eritreo" },
  { code: "ETB", label: "ETB — Birr etíope" },
  { code: "EUR", label: "EUR — Euro" },
  { code: "FJD", label: "FJD — Dólar fiyiano" },
  { code: "FKP", label: "FKP — Libra malvinense" },
  { code: "GBP", label: "GBP — Libra esterlina" },
  { code: "GEL", label: "GEL — Lari georgiano" },
  { code: "GHS", label: "GHS — Cedi ghanés" },
  { code: "GIP", label: "GIP — Libra gibraltareña" },
  { code: "GMD", label: "GMD — Dalasi gambiano" },
  { code: "GTQ", label: "GTQ — Quetzal guatemalteco" },
  { code: "GYD", label: "GYD — Dólar guyanés" },
  { code: "HKD", label: "HKD — Dólar de Hong Kong" },
  { code: "HNL", label: "HNL — Lempira hondureño" },
  { code: "HRK", label: "HRK — Kuna croata" },
  { code: "HTG", label: "HTG — Gourde haitiano" },
  { code: "HUF", label: "HUF — Forinto húngaro" },
  { code: "IDR", label: "IDR — Rupia indonesia" },
  { code: "ILS", label: "ILS — Séquel israelí" },
  { code: "INR", label: "INR — Rupia india" },
  { code: "IQD", label: "IQD — Dinar iraquí" },
  { code: "IRR", label: "IRR — Rial iraní" },
  { code: "ISK", label: "ISK — Corona islandesa" },
  { code: "JMD", label: "JMD — Dólar jamaicano" },
  { code: "JOD", label: "JOD — Dinar jordano" },
  { code: "JPY", label: "JPY — Yen japonés" },
  { code: "KES", label: "KES — Chelín keniano" },
  { code: "KGS", label: "KGS — Som kirguís" },
  { code: "KHR", label: "KHR — Riel camboyano" },
  { code: "KRW", label: "KRW — Won surcoreano" },
  { code: "KWD", label: "KWD — Dinar kuwaití" },
  { code: "KYD", label: "KYD — Dólar de las Islas Caimán" },
  { code: "KZT", label: "KZT — Tenge kazajo" },
  { code: "LAK", label: "LAK — Kip laosiano" },
  { code: "LBP", label: "LBP — Libra libanesa" },
  { code: "LKR", label: "LKR — Rupia de Sri Lanka" },
  { code: "LRD", label: "LRD — Dólar liberiano" },
  { code: "LYD", label: "LYD — Dinar libio" },
  { code: "MAD", label: "MAD — Dírham marroquí" },
  { code: "MDL", label: "MDL — Leu moldavo" },
  { code: "MKD", label: "MKD — Denar macedonio" },
  { code: "MMK", label: "MMK — Kyat birmano" },
  { code: "MNT", label: "MNT — Tugrik mongol" },
  { code: "MOP", label: "MOP — Pataca macaense" },
  { code: "MUR", label: "MUR — Rupia mauriciana" },
  { code: "MVR", label: "MVR — Rufiyaa maldiva" },
  { code: "MWK", label: "MWK — Kwacha malauí" },
  { code: "MXN", label: "MXN — Peso mexicano" },
  { code: "MYR", label: "MYR — Ringgit malayo" },
  { code: "MZN", label: "MZN — Metical mozambiqueño" },
  { code: "NAD", label: "NAD — Dólar namibio" },
  { code: "NGN", label: "NGN — Naira nigeriana" },
  { code: "NIO", label: "NIO — Córdoba nicaragüense" },
  { code: "NOK", label: "NOK — Corona noruega" },
  { code: "NPR", label: "NPR — Rupia nepalesa" },
  { code: "NZD", label: "NZD — Dólar neozelandés" },
  { code: "OMR", label: "OMR — Rial omaní" },
  { code: "PAB", label: "PAB — Balboa panameño" },
  { code: "PEN", label: "PEN — Sol peruano" },
  { code: "PGK", label: "PGK — Kina de Papúa Nueva Guinea" },
  { code: "PHP", label: "PHP — Peso filipino" },
  { code: "PKR", label: "PKR — Rupia pakistaní" },
  { code: "PLN", label: "PLN — Esloti polaco" },
  { code: "PYG", label: "PYG — Guaraní paraguayo" },
  { code: "QAR", label: "QAR — Riyal catarí" },
  { code: "RON", label: "RON — Leu rumano" },
  { code: "RSD", label: "RSD — Dinar serbio" },
  { code: "RUB", label: "RUB — Rublo ruso" },
  { code: "RWF", label: "RWF — Franco ruandés" },
  { code: "SAR", label: "SAR — Riyal saudí" },
  { code: "SBD", label: "SBD — Dólar de las Islas Salomón" },
  { code: "SCR", label: "SCR — Rupia de Seychelles" },
  { code: "SDG", label: "SDG — Libra sudanesa" },
  { code: "SEK", label: "SEK — Corona sueca" },
  { code: "SGD", label: "SGD — Dólar de Singapur" },
  { code: "SLL", label: "SLL — Leone de Sierra Leona" },
  { code: "SOS", label: "SOS — Chelín somalí" },
  { code: "SRD", label: "SRD — Dólar surinamés" },
  { code: "STN", label: "STN — Dobra de Santo Tomé" },
  { code: "SYP", label: "SYP — Libra siria" },
  { code: "SZL", label: "SZL — Lilangeni suazi" },
  { code: "THB", label: "THB — Baht tailandés" },
  { code: "TJS", label: "TJS — Somoni tayiko" },
  { code: "TMT", label: "TMT — Manat turcomano" },
  { code: "TND", label: "TND — Dinar tunecino" },
  { code: "TOP", label: "TOP — Pa'anga tongano" },
  { code: "TRY", label: "TRY — Lira turca" },
  { code: "TTD", label: "TTD — Dólar de Trinidad y Tobago" },
  { code: "TWD", label: "TWD — Nuevo dólar taiwanés" },
  { code: "TZS", label: "TZS — Chelín tanzano" },
  { code: "UAH", label: "UAH — Grivna ucraniana" },
  { code: "UGX", label: "UGX — Chelín ugandés" },
  { code: "USD", label: "USD — Dólar estadounidense" },
  { code: "UYU", label: "UYU — Peso uruguayo" },
  { code: "UZS", label: "UZS — Som uzbeko" },
  { code: "VES", label: "VES — Bolívar venezolano" },
  { code: "VND", label: "VND — Dong vietnamita" },
  { code: "VUV", label: "VUV — Vatu de Vanuatu" },
  { code: "WST", label: "WST — Tālā samoano" },
  { code: "XAF", label: "XAF — Franco CFA de África Central" },
  { code: "XCD", label: "XCD — Dólar del Caribe Oriental" },
  { code: "XOF", label: "XOF — Franco CFA de África Occidental" },
  { code: "YER", label: "YER — Rial yemení" },
  { code: "ZAR", label: "ZAR — Rand sudafricano" },
  { code: "ZMW", label: "ZMW — Kwacha zambiano" },
  { code: "ZWL", label: "ZWL — Dólar zimbabuense" },
] as const;

/** Industry values for company "business activity". Labels are translated via companies.industryOptions.<value> in i18n. */
export const INDUSTRIES = [
  { value: "PARKING_OPERATOR" },
  { value: "MALL" },
  { value: "SUPERMARKET_RETAIL_CHAIN" },
  { value: "HOSPITAL_CLINIC" },
  { value: "HOTEL" },
  { value: "AIRPORT" },
  { value: "OFFICE_BUILDING" },
  { value: "RESIDENTIAL" },
  { value: "UNIVERSITY_SCHOOL" },
  { value: "EVENT_VENUE" },
  { value: "MUNICIPALITY" },
  { value: "INDUSTRIAL_MANUFACTURING" },
  { value: "LOGISTICS_WAREHOUSING" },
  { value: "BANKING_FINANCIAL" },
  { value: "TECH" },
  { value: "RESTAURANTS_FOOD" },
  { value: "ENTERTAINMENT_LEISURE" },
  { value: "EDUCATION" },
  { value: "OTHER" },
] as const;

export const LICENSE_TYPES = [
  { value: "A1", label: "A1 — Motocicletas hasta 250cc" },
  { value: "A2", label: "A2 — Motocicletas hasta 750cc" },
  { value: "A3", label: "A3 — Motocicletas sin restricción" },
  { value: "B1", label: "B1 — Automóviles y camionetas" },
  { value: "B2", label: "B2 — Vehículos de carga no articulados" },
  { value: "C",  label: "C — Vehículos de carga pesada" },
  { value: "D1", label: "D1 — Autobuses interurbanos" },
  { value: "D2", label: "D2 — Microbuses y buses" },
  { value: "D3", label: "D3 — Taxi y transporte especial" },
  { value: "E",  label: "E — Maquinaria pesada" },
  { value: "F",  label: "F — Vehículos especiales" },
] as const;

/** Generates a human-readable label from an IANA timezone ID.
 * Replaces underscores with spaces and computes the live UTC offset via Intl (DST-aware).
 * Use this wherever a raw IANA ID needs to be displayed to the user.
 */
export function makeTzLabel(ianaId: string): string {
  const name = ianaId.replace(/_/g, ' ');
  try {
    const offset = new Intl.DateTimeFormat('en', {
      timeZone: ianaId,
      timeZoneName: 'shortOffset',
    })
      .formatToParts(new Date())
      .find((p) => p.type === 'timeZoneName')?.value ?? '';
    return offset ? `${name}  (${offset})` : name;
  } catch {
    return name;
  }
}

const TIMEZONE_IDS = [
  // África
  'Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers',
  'Africa/Cairo', 'Africa/Casablanca', 'Africa/Johannesburg', 'Africa/Kampala',
  'Africa/Lagos', 'Africa/Nairobi', 'Africa/Tunis',
  // América — Norteamérica
  'America/Anchorage', 'America/Chicago', 'America/Denver', 'America/Detroit',
  'America/Los_Angeles', 'America/New_York', 'America/Phoenix',
  // América — México
  'America/Cancun', 'America/Chihuahua', 'America/Hermosillo', 'America/Mazatlan',
  'America/Mexico_City', 'America/Monterrey', 'America/Tijuana',
  // América — Centroamérica
  'America/Belize', 'America/Costa_Rica', 'America/El_Salvador', 'America/Guatemala',
  'America/Managua', 'America/Panama', 'America/Tegucigalpa',
  // América — Caribe
  'America/Havana', 'America/Jamaica', 'America/Port-au-Prince',
  'America/Puerto_Rico', 'America/Santo_Domingo',
  // América — Sudamérica Norte
  'America/Bogota', 'America/Caracas', 'America/Guayaquil',
  'America/Guyana', 'America/Lima', 'America/Paramaribo',
  // América — Sudamérica Sur
  'America/Argentina/Buenos_Aires', 'America/Argentina/Cordoba',
  'America/Asuncion', 'America/La_Paz', 'America/Manaus',
  'America/Montevideo', 'America/Santiago', 'America/Sao_Paulo',
  // Canadá
  'America/Edmonton', 'America/Halifax', 'America/St_Johns',
  'America/Toronto', 'America/Vancouver', 'America/Winnipeg',
  // Asia — Oriente Medio
  'Asia/Aden', 'Asia/Amman', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Beirut',
  'Asia/Damascus', 'Asia/Dubai', 'Asia/Jerusalem', 'Asia/Kuwait',
  'Asia/Muscat', 'Asia/Qatar', 'Asia/Riyadh', 'Asia/Tehran',
  // Asia — Centro y Sur
  'Asia/Baku', 'Asia/Colombo', 'Asia/Dhaka', 'Asia/Kabul', 'Asia/Karachi',
  'Asia/Kathmandu', 'Asia/Kolkata', 'Asia/Tashkent', 'Asia/Tbilisi', 'Asia/Yerevan',
  // Asia — Sudeste y Este
  'Asia/Bangkok', 'Asia/Hong_Kong', 'Asia/Ho_Chi_Minh', 'Asia/Jakarta',
  'Asia/Kuala_Lumpur', 'Asia/Makassar', 'Asia/Manila', 'Asia/Yangon',
  'Asia/Seoul', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Taipei',
  'Asia/Tokyo', 'Asia/Ulaanbaatar',
  // Europa
  'Europe/Amsterdam', 'Europe/Athens', 'Europe/Belgrade', 'Europe/Berlin',
  'Europe/Brussels', 'Europe/Bucharest', 'Europe/Budapest', 'Europe/Copenhagen',
  'Europe/Dublin', 'Europe/Helsinki', 'Europe/Istanbul', 'Europe/Kyiv',
  'Europe/Lisbon', 'Europe/London', 'Europe/Luxembourg', 'Europe/Madrid',
  'Europe/Minsk', 'Europe/Moscow', 'Europe/Oslo', 'Europe/Paris',
  'Europe/Prague', 'Europe/Rome', 'Europe/Sofia', 'Europe/Stockholm',
  'Europe/Tallinn', 'Europe/Vienna', 'Europe/Warsaw', 'Europe/Zurich',
  // Pacífico y Oceanía
  'Australia/Adelaide', 'Australia/Brisbane', 'Australia/Darwin',
  'Australia/Perth', 'Australia/Sydney',
  'Pacific/Auckland', 'Pacific/Fiji', 'Pacific/Guam',
  'Pacific/Honolulu', 'Pacific/Port_Moresby', 'Pacific/Tongatapu',
  // UTC
  'UTC',
] as const;

export const TIMEZONES: { value: string; label: string }[] = TIMEZONE_IDS.map((id) => ({
  value: id,
  label: makeTzLabel(id),
}));
