export const COUNTRIES = [
  { code: "AF", label: "Afganistán" },
  { code: "AL", label: "Albania" },
  { code: "DE", label: "Alemania" },
  { code: "AD", label: "Andorra" },
  { code: "AO", label: "Angola" },
  { code: "AI", label: "Anguila" },
  { code: "AG", label: "Antigua y Barbuda" },
  { code: "SA", label: "Arabia Saudita" },
  { code: "DZ", label: "Argelia" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Armenia" },
  { code: "AW", label: "Aruba" },
  { code: "AU", label: "Australia" },
  { code: "AT", label: "Austria" },
  { code: "AZ", label: "Azerbaiyán" },
  { code: "BS", label: "Bahamas" },
  { code: "BH", label: "Baréin" },
  { code: "BD", label: "Bangladés" },
  { code: "BB", label: "Barbados" },
  { code: "BE", label: "Bélgica" },
  { code: "BZ", label: "Belice" },
  { code: "BJ", label: "Benín" },
  { code: "BM", label: "Bermudas" },
  { code: "BY", label: "Bielorrusia" },
  { code: "BO", label: "Bolivia" },
  { code: "BA", label: "Bosnia y Herzegovina" },
  { code: "BW", label: "Botsuana" },
  { code: "BR", label: "Brasil" },
  { code: "BN", label: "Brunéi" },
  { code: "BG", label: "Bulgaria" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "BT", label: "Bután" },
  { code: "CV", label: "Cabo Verde" },
  { code: "KH", label: "Camboya" },
  { code: "CM", label: "Camerún" },
  { code: "CA", label: "Canadá" },
  { code: "QA", label: "Catar" },
  { code: "TD", label: "Chad" },
  { code: "CL", label: "Chile" },
  { code: "CN", label: "China" },
  { code: "CY", label: "Chipre" },
  { code: "VA", label: "Ciudad del Vaticano" },
  { code: "CO", label: "Colombia" },
  { code: "KM", label: "Comoras" },
  { code: "CG", label: "Congo" },
  { code: "CD", label: "Congo (R.D.)" },
  { code: "KP", label: "Corea del Norte" },
  { code: "KR", label: "Corea del Sur" },
  { code: "CR", label: "Costa Rica" },
  { code: "CI", label: "Costa de Marfil" },
  { code: "HR", label: "Croacia" },
  { code: "CU", label: "Cuba" },
  { code: "CW", label: "Curazao" },
  { code: "DK", label: "Dinamarca" },
  { code: "DM", label: "Dominica" },
  { code: "EC", label: "Ecuador" },
  { code: "EG", label: "Egipto" },
  { code: "SV", label: "El Salvador" },
  { code: "AE", label: "Emiratos Árabes Unidos" },
  { code: "ER", label: "Eritrea" },
  { code: "SK", label: "Eslovaquia" },
  { code: "SI", label: "Eslovenia" },
  { code: "ES", label: "España" },
  { code: "US", label: "Estados Unidos" },
  { code: "EE", label: "Estonia" },
  { code: "ET", label: "Etiopía" },
  { code: "PH", label: "Filipinas" },
  { code: "FI", label: "Finlandia" },
  { code: "FJ", label: "Fiyi" },
  { code: "FR", label: "Francia" },
  { code: "GA", label: "Gabón" },
  { code: "GM", label: "Gambia" },
  { code: "GE", label: "Georgia" },
  { code: "GH", label: "Ghana" },
  { code: "GI", label: "Gibraltar" },
  { code: "GD", label: "Granada" },
  { code: "GR", label: "Grecia" },
  { code: "GL", label: "Groenlandia" },
  { code: "GP", label: "Guadalupe" },
  { code: "GT", label: "Guatemala" },
  { code: "GN", label: "Guinea" },
  { code: "GW", label: "Guinea-Bisáu" },
  { code: "GQ", label: "Guinea Ecuatorial" },
  { code: "GY", label: "Guyana" },
  { code: "GF", label: "Guyana Francesa" },
  { code: "HT", label: "Haití" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "HU", label: "Hungría" },
  { code: "IN", label: "India" },
  { code: "ID", label: "Indonesia" },
  { code: "IQ", label: "Irak" },
  { code: "IR", label: "Irán" },
  { code: "IE", label: "Irlanda" },
  { code: "IS", label: "Islandia" },
  { code: "MH", label: "Islas Marshall" },
  { code: "SB", label: "Islas Salomón" },
  { code: "IL", label: "Israel" },
  { code: "IT", label: "Italia" },
  { code: "JM", label: "Jamaica" },
  { code: "JP", label: "Japón" },
  { code: "JO", label: "Jordania" },
  { code: "KZ", label: "Kazajistán" },
  { code: "KE", label: "Kenia" },
  { code: "KG", label: "Kirguistán" },
  { code: "KI", label: "Kiribati" },
  { code: "KW", label: "Kuwait" },
  { code: "LA", label: "Laos" },
  { code: "LS", label: "Lesoto" },
  { code: "LV", label: "Letonia" },
  { code: "LB", label: "Líbano" },
  { code: "LR", label: "Liberia" },
  { code: "LY", label: "Libia" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lituania" },
  { code: "LU", label: "Luxemburgo" },
  { code: "MO", label: "Macao" },
  { code: "MG", label: "Madagascar" },
  { code: "MY", label: "Malasia" },
  { code: "MW", label: "Malaui" },
  { code: "MV", label: "Maldivas" },
  { code: "ML", label: "Malí" },
  { code: "MT", label: "Malta" },
  { code: "MA", label: "Marruecos" },
  { code: "MQ", label: "Martinica" },
  { code: "MU", label: "Mauricio" },
  { code: "MR", label: "Mauritania" },
  { code: "MX", label: "México" },
  { code: "FM", label: "Micronesia" },
  { code: "MD", label: "Moldavia" },
  { code: "MC", label: "Mónaco" },
  { code: "MN", label: "Mongolia" },
  { code: "ME", label: "Montenegro" },
  { code: "MS", label: "Montserrat" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibia" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Níger" },
  { code: "NG", label: "Nigeria" },
  { code: "NO", label: "Noruega" },
  { code: "NZ", label: "Nueva Zelanda" },
  { code: "OM", label: "Omán" },
  { code: "NL", label: "Países Bajos" },
  { code: "PK", label: "Pakistán" },
  { code: "PW", label: "Palaos" },
  { code: "PA", label: "Panamá" },
  { code: "PG", label: "Papúa Nueva Guinea" },
  { code: "PY", label: "Paraguay" },
  { code: "PE", label: "Perú" },
  { code: "PL", label: "Polonia" },
  { code: "PT", label: "Portugal" },
  { code: "PR", label: "Puerto Rico" },
  { code: "GB", label: "Reino Unido" },
  { code: "CZ", label: "República Checa" },
  { code: "DO", label: "República Dominicana" },
  { code: "CF", label: "República Centroafricana" },
  { code: "RE", label: "Reunión" },
  { code: "RW", label: "Ruanda" },
  { code: "RO", label: "Rumanía" },
  { code: "RU", label: "Rusia" },
  { code: "WS", label: "Samoa" },
  { code: "KN", label: "San Cristóbal y Nieves" },
  { code: "SM", label: "San Marino" },
  { code: "VC", label: "San Vicente y las Granadinas" },
  { code: "SH", label: "Santa Elena" },
  { code: "LC", label: "Santa Lucía" },
  { code: "ST", label: "Santo Tomé y Príncipe" },
  { code: "SN", label: "Senegal" },
  { code: "RS", label: "Serbia" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leona" },
  { code: "SG", label: "Singapur" },
  { code: "SO", label: "Somalia" },
  { code: "LK", label: "Sri Lanka" },
  { code: "SZ", label: "Suazilandia" },
  { code: "ZA", label: "Sudáfrica" },
  { code: "SD", label: "Sudán" },
  { code: "SS", label: "Sudán del Sur" },
  { code: "SE", label: "Suecia" },
  { code: "CH", label: "Suiza" },
  { code: "SR", label: "Surinam" },
  { code: "TH", label: "Tailandia" },
  { code: "TW", label: "Taiwán" },
  { code: "TZ", label: "Tanzania" },
  { code: "TJ", label: "Tayikistán" },
  { code: "TL", label: "Timor Oriental" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad y Tobago" },
  { code: "TN", label: "Túnez" },
  { code: "TM", label: "Turkmenistán" },
  { code: "TR", label: "Turquía" },
  { code: "TV", label: "Tuvalu" },
  { code: "UA", label: "Ucrania" },
  { code: "UG", label: "Uganda" },
  { code: "UY", label: "Uruguay" },
  { code: "UZ", label: "Uzbekistán" },
  { code: "VU", label: "Vanuatu" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "YE", label: "Yemen" },
  { code: "DJ", label: "Yibuti" },
  { code: "ZM", label: "Zambia" },
  { code: "ZW", label: "Zimbabue" },
] as const;

export const CURRENCIES = [
  { code: "AED", label: "AED — Dírham de los EAU" },
  { code: "AFN", label: "AFN — Afgani afgano" },
  { code: "ALL", label: "ALL — Lek albanés" },
  { code: "AMD", label: "AMD — Dram armenio" },
  { code: "ANG", label: "ANG — Florín antillano" },
  { code: "AOA", label: "AOA — Kwanza angoleño" },
  { code: "ARS", label: "ARS — Peso argentino" },
  { code: "AUD", label: "AUD — Dólar australiano" },
  { code: "AWG", label: "AWG — Florín arubeño" },
  { code: "AZN", label: "AZN — Manat azerbaiyano" },
  { code: "BAM", label: "BAM — Marco bosnio-herzegovino" },
  { code: "BBD", label: "BBD — Dólar de Barbados" },
  { code: "BDT", label: "BDT — Taka bangladesí" },
  { code: "BGN", label: "BGN — Lev búlgaro" },
  { code: "BHD", label: "BHD — Dinar bareiní" },
  { code: "BIF", label: "BIF — Franco burundés" },
  { code: "BMD", label: "BMD — Dólar de Bermudas" },
  { code: "BND", label: "BND — Dólar de Brunéi" },
  { code: "BOB", label: "BOB — Boliviano" },
  { code: "BRL", label: "BRL — Real brasileño" },
  { code: "BSD", label: "BSD — Dólar de las Bahamas" },
  { code: "BTN", label: "BTN — Ngultrum butanés" },
  { code: "BWP", label: "BWP — Pula botsuanesa" },
  { code: "BYN", label: "BYN — Rublo bielorruso" },
  { code: "BZD", label: "BZD — Dólar de Belice" },
  { code: "CAD", label: "CAD — Dólar canadiense" },
  { code: "CDF", label: "CDF — Franco congoleño" },
  { code: "CHF", label: "CHF — Franco suizo" },
  { code: "CLP", label: "CLP — Peso chileno" },
  { code: "CNY", label: "CNY — Yuan chino" },
  { code: "COP", label: "COP — Peso colombiano" },
  { code: "CRC", label: "CRC — Colón costarricense" },
  { code: "CUP", label: "CUP — Peso cubano" },
  { code: "CVE", label: "CVE — Escudo caboverdiano" },
  { code: "CZK", label: "CZK — Corona checa" },
  { code: "DJF", label: "DJF — Franco yibutiano" },
  { code: "DKK", label: "DKK — Corona danesa" },
  { code: "DOP", label: "DOP — Peso dominicano" },
  { code: "DZD", label: "DZD — Dinar argelino" },
  { code: "EGP", label: "EGP — Libra egipcia" },
  { code: "ERN", label: "ERN — Nakfa eritreo" },
  { code: "ETB", label: "ETB — Birr etíope" },
  { code: "EUR", label: "EUR — Euro" },
  { code: "FJD", label: "FJD — Dólar fiyiano" },
  { code: "FKP", label: "FKP — Libra malvinense" },
  { code: "GBP", label: "GBP — Libra esterlina" },
  { code: "GEL", label: "GEL — Lari georgiano" },
  { code: "GHS", label: "GHS — Cedi ghanés" },
  { code: "GIP", label: "GIP — Libra gibraltareña" },
  { code: "GMD", label: "GMD — Dalasi gambiano" },
  { code: "GTQ", label: "GTQ — Quetzal guatemalteco" },
  { code: "GYD", label: "GYD — Dólar guyanés" },
  { code: "HKD", label: "HKD — Dólar de Hong Kong" },
  { code: "HNL", label: "HNL — Lempira hondureño" },
  { code: "HRK", label: "HRK — Kuna croata" },
  { code: "HTG", label: "HTG — Gourde haitiano" },
  { code: "HUF", label: "HUF — Forinto húngaro" },
  { code: "IDR", label: "IDR — Rupia indonesia" },
  { code: "ILS", label: "ILS — Séquel israelí" },
  { code: "INR", label: "INR — Rupia india" },
  { code: "IQD", label: "IQD — Dinar iraquí" },
  { code: "IRR", label: "IRR — Rial iraní" },
  { code: "ISK", label: "ISK — Corona islandesa" },
  { code: "JMD", label: "JMD — Dólar jamaicano" },
  { code: "JOD", label: "JOD — Dinar jordano" },
  { code: "JPY", label: "JPY — Yen japonés" },
  { code: "KES", label: "KES — Chelín keniano" },
  { code: "KGS", label: "KGS — Som kirguís" },
  { code: "KHR", label: "KHR — Riel camboyano" },
  { code: "KRW", label: "KRW — Won surcoreano" },
  { code: "KWD", label: "KWD — Dinar kuwaití" },
  { code: "KYD", label: "KYD — Dólar de las Islas Caimán" },
  { code: "KZT", label: "KZT — Tenge kazajo" },
  { code: "LAK", label: "LAK — Kip laosiano" },
  { code: "LBP", label: "LBP — Libra libanesa" },
  { code: "LKR", label: "LKR — Rupia de Sri Lanka" },
  { code: "LRD", label: "LRD — Dólar liberiano" },
  { code: "LYD", label: "LYD — Dinar libio" },
  { code: "MAD", label: "MAD — Dírham marroquí" },
  { code: "MDL", label: "MDL — Leu moldavo" },
  { code: "MKD", label: "MKD — Denar macedonio" },
  { code: "MMK", label: "MMK — Kyat birmano" },
  { code: "MNT", label: "MNT — Tugrik mongol" },
  { code: "MOP", label: "MOP — Pataca macaense" },
  { code: "MUR", label: "MUR — Rupia mauriciana" },
  { code: "MVR", label: "MVR — Rufiyaa maldiva" },
  { code: "MWK", label: "MWK — Kwacha malauí" },
  { code: "MXN", label: "MXN — Peso mexicano" },
  { code: "MYR", label: "MYR — Ringgit malayo" },
  { code: "MZN", label: "MZN — Metical mozambiqueño" },
  { code: "NAD", label: "NAD — Dólar namibio" },
  { code: "NGN", label: "NGN — Naira nigeriana" },
  { code: "NIO", label: "NIO — Córdoba nicaragüense" },
  { code: "NOK", label: "NOK — Corona noruega" },
  { code: "NPR", label: "NPR — Rupia nepalesa" },
  { code: "NZD", label: "NZD — Dólar neozelandés" },
  { code: "OMR", label: "OMR — Rial omaní" },
  { code: "PAB", label: "PAB — Balboa panameño" },
  { code: "PEN", label: "PEN — Sol peruano" },
  { code: "PGK", label: "PGK — Kina de Papúa Nueva Guinea" },
  { code: "PHP", label: "PHP — Peso filipino" },
  { code: "PKR", label: "PKR — Rupia pakistaní" },
  { code: "PLN", label: "PLN — Esloti polaco" },
  { code: "PYG", label: "PYG — Guaraní paraguayo" },
  { code: "QAR", label: "QAR — Riyal catarí" },
  { code: "RON", label: "RON — Leu rumano" },
  { code: "RSD", label: "RSD — Dinar serbio" },
  { code: "RUB", label: "RUB — Rublo ruso" },
  { code: "RWF", label: "RWF — Franco ruandés" },
  { code: "SAR", label: "SAR — Riyal saudí" },
  { code: "SBD", label: "SBD — Dólar de las Islas Salomón" },
  { code: "SCR", label: "SCR — Rupia de Seychelles" },
  { code: "SDG", label: "SDG — Libra sudanesa" },
  { code: "SEK", label: "SEK — Corona sueca" },
  { code: "SGD", label: "SGD — Dólar de Singapur" },
  { code: "SLL", label: "SLL — Leone de Sierra Leona" },
  { code: "SOS", label: "SOS — Chelín somalí" },
  { code: "SRD", label: "SRD — Dólar surinamés" },
  { code: "STN", label: "STN — Dobra de Santo Tomé" },
  { code: "SYP", label: "SYP — Libra siria" },
  { code: "SZL", label: "SZL — Lilangeni suazi" },
  { code: "THB", label: "THB — Baht tailandés" },
  { code: "TJS", label: "TJS — Somoni tayiko" },
  { code: "TMT", label: "TMT — Manat turcomano" },
  { code: "TND", label: "TND — Dinar tunecino" },
  { code: "TOP", label: "TOP — Pa'anga tongano" },
  { code: "TRY", label: "TRY — Lira turca" },
  { code: "TTD", label: "TTD — Dólar de Trinidad y Tobago" },
  { code: "TWD", label: "TWD — Nuevo dólar taiwanés" },
  { code: "TZS", label: "TZS — Chelín tanzano" },
  { code: "UAH", label: "UAH — Grivna ucraniana" },
  { code: "UGX", label: "UGX — Chelín ugandés" },
  { code: "USD", label: "USD — Dólar estadounidense" },
  { code: "UYU", label: "UYU — Peso uruguayo" },
  { code: "UZS", label: "UZS — Som uzbeko" },
  { code: "VES", label: "VES — Bolívar venezolano" },
  { code: "VND", label: "VND — Dong vietnamita" },
  { code: "VUV", label: "VUV — Vatu de Vanuatu" },
  { code: "WST", label: "WST — Tālā samoano" },
  { code: "XAF", label: "XAF — Franco CFA de África Central" },
  { code: "XCD", label: "XCD — Dólar del Caribe Oriental" },
  { code: "XOF", label: "XOF — Franco CFA de África Occidental" },
  { code: "YER", label: "YER — Rial yemení" },
  { code: "ZAR", label: "ZAR — Rand sudafricano" },
  { code: "ZMW", label: "ZMW — Kwacha zambiano" },
  { code: "ZWL", label: "ZWL — Dólar zimbabuense" },
] as const;

export const TIMEZONES = [
  // África
  { value: "Africa/Abidjan",             label: "Africa/Abidjan  (UTC+0)" },
  { value: "Africa/Accra",               label: "Africa/Accra  (UTC+0)" },
  { value: "Africa/Addis_Ababa",         label: "Africa/Addis_Ababa  (UTC+3)" },
  { value: "Africa/Algiers",             label: "Africa/Algiers  (UTC+1)" },
  { value: "Africa/Cairo",               label: "Africa/Cairo  (UTC+2)" },
  { value: "Africa/Casablanca",          label: "Africa/Casablanca  (UTC+1)" },
  { value: "Africa/Johannesburg",        label: "Africa/Johannesburg  (UTC+2)" },
  { value: "Africa/Kampala",             label: "Africa/Kampala  (UTC+3)" },
  { value: "Africa/Lagos",               label: "Africa/Lagos  (UTC+1)" },
  { value: "Africa/Nairobi",             label: "Africa/Nairobi  (UTC+3)" },
  { value: "Africa/Tunis",               label: "Africa/Tunis  (UTC+1)" },
  // América — Norteamérica
  { value: "America/Anchorage",          label: "America/Anchorage  (UTC-9/-8)" },
  { value: "America/Chicago",            label: "America/Chicago  (UTC-6/-5)" },
  { value: "America/Denver",             label: "America/Denver  (UTC-7/-6)" },
  { value: "America/Detroit",            label: "America/Detroit  (UTC-5/-4)" },
  { value: "America/Los_Angeles",        label: "America/Los_Angeles  (UTC-8/-7)" },
  { value: "America/New_York",           label: "America/New_York  (UTC-5/-4)" },
  { value: "America/Phoenix",            label: "America/Phoenix  (UTC-7)" },
  // América — México
  { value: "America/Cancun",             label: "America/Cancun  (UTC-5)" },
  { value: "America/Chihuahua",          label: "America/Chihuahua  (UTC-7/-6)" },
  { value: "America/Hermosillo",         label: "America/Hermosillo  (UTC-7)" },
  { value: "America/Mazatlan",           label: "America/Mazatlan  (UTC-7/-6)" },
  { value: "America/Mexico_City",        label: "America/Mexico_City  (UTC-6/-5)" },
  { value: "America/Monterrey",          label: "America/Monterrey  (UTC-6/-5)" },
  { value: "America/Tijuana",            label: "America/Tijuana  (UTC-8/-7)" },
  // América — Centroamérica
  { value: "America/Belize",             label: "America/Belize  (UTC-6)" },
  { value: "America/Costa_Rica",         label: "America/Costa_Rica  (UTC-6)" },
  { value: "America/El_Salvador",        label: "America/El_Salvador  (UTC-6)" },
  { value: "America/Guatemala",          label: "America/Guatemala  (UTC-6)" },
  { value: "America/Managua",            label: "America/Managua  (UTC-6)" },
  { value: "America/Panama",             label: "America/Panama  (UTC-5)" },
  { value: "America/Tegucigalpa",        label: "America/Tegucigalpa  (UTC-6)" },
  // América — Caribe
  { value: "America/Havana",             label: "America/Havana  (UTC-5/-4)" },
  { value: "America/Jamaica",            label: "America/Jamaica  (UTC-5)" },
  { value: "America/Port-au-Prince",     label: "America/Port-au-Prince  (UTC-5/-4)" },
  { value: "America/Puerto_Rico",        label: "America/Puerto_Rico  (UTC-4)" },
  { value: "America/Santo_Domingo",      label: "America/Santo_Domingo  (UTC-4)" },
  // América — Sudamérica Norte
  { value: "America/Bogota",             label: "America/Bogota  (UTC-5)" },
  { value: "America/Caracas",            label: "America/Caracas  (UTC-4)" },
  { value: "America/Guayaquil",          label: "America/Guayaquil  (UTC-5)" },
  { value: "America/Guyana",             label: "America/Guyana  (UTC-4)" },
  { value: "America/Lima",               label: "America/Lima  (UTC-5)" },
  { value: "America/Paramaribo",         label: "America/Paramaribo  (UTC-3)" },
  // América — Sudamérica Sur
  { value: "America/Argentina/Buenos_Aires", label: "America/Argentina/Buenos_Aires  (UTC-3)" },
  { value: "America/Argentina/Cordoba",  label: "America/Argentina/Cordoba  (UTC-3)" },
  { value: "America/Asuncion",           label: "America/Asuncion  (UTC-4/-3)" },
  { value: "America/La_Paz",             label: "America/La_Paz  (UTC-4)" },
  { value: "America/Manaus",             label: "America/Manaus  (UTC-4)" },
  { value: "America/Montevideo",         label: "America/Montevideo  (UTC-3)" },
  { value: "America/Santiago",           label: "America/Santiago  (UTC-4/-3)" },
  { value: "America/Sao_Paulo",          label: "America/Sao_Paulo  (UTC-3/-2)" },
  // Canadá
  { value: "America/Edmonton",           label: "America/Edmonton  (UTC-7/-6)" },
  { value: "America/Halifax",            label: "America/Halifax  (UTC-4/-3)" },
  { value: "America/St_Johns",           label: "America/St_Johns  (UTC-3:30/-2:30)" },
  { value: "America/Toronto",            label: "America/Toronto  (UTC-5/-4)" },
  { value: "America/Vancouver",          label: "America/Vancouver  (UTC-8/-7)" },
  { value: "America/Winnipeg",           label: "America/Winnipeg  (UTC-6/-5)" },
  // Asia — Oriente Medio
  { value: "Asia/Aden",                  label: "Asia/Aden  (UTC+3)" },
  { value: "Asia/Amman",                 label: "Asia/Amman  (UTC+3)" },
  { value: "Asia/Baghdad",               label: "Asia/Baghdad  (UTC+3)" },
  { value: "Asia/Bahrain",               label: "Asia/Bahrain  (UTC+3)" },
  { value: "Asia/Beirut",                label: "Asia/Beirut  (UTC+2/+3)" },
  { value: "Asia/Damascus",              label: "Asia/Damascus  (UTC+3)" },
  { value: "Asia/Dubai",                 label: "Asia/Dubai  (UTC+4)" },
  { value: "Asia/Jerusalem",             label: "Asia/Jerusalem  (UTC+2/+3)" },
  { value: "Asia/Kuwait",                label: "Asia/Kuwait  (UTC+3)" },
  { value: "Asia/Muscat",                label: "Asia/Muscat  (UTC+4)" },
  { value: "Asia/Qatar",                 label: "Asia/Qatar  (UTC+3)" },
  { value: "Asia/Riyadh",                label: "Asia/Riyadh  (UTC+3)" },
  { value: "Asia/Tehran",                label: "Asia/Tehran  (UTC+3:30/+4:30)" },
  // Asia — Centro y Sur
  { value: "Asia/Baku",                  label: "Asia/Baku  (UTC+4)" },
  { value: "Asia/Colombo",               label: "Asia/Colombo  (UTC+5:30)" },
  { value: "Asia/Dhaka",                 label: "Asia/Dhaka  (UTC+6)" },
  { value: "Asia/Kabul",                 label: "Asia/Kabul  (UTC+4:30)" },
  { value: "Asia/Karachi",               label: "Asia/Karachi  (UTC+5)" },
  { value: "Asia/Kathmandu",             label: "Asia/Kathmandu  (UTC+5:45)" },
  { value: "Asia/Kolkata",               label: "Asia/Kolkata  (UTC+5:30)" },
  { value: "Asia/Tashkent",              label: "Asia/Tashkent  (UTC+5)" },
  { value: "Asia/Tbilisi",               label: "Asia/Tbilisi  (UTC+4)" },
  { value: "Asia/Yerevan",               label: "Asia/Yerevan  (UTC+4)" },
  // Asia — Sudeste y Este
  { value: "Asia/Bangkok",               label: "Asia/Bangkok  (UTC+7)" },
  { value: "Asia/Hong_Kong",             label: "Asia/Hong_Kong  (UTC+8)" },
  { value: "Asia/Ho_Chi_Minh",           label: "Asia/Ho_Chi_Minh  (UTC+7)" },
  { value: "Asia/Jakarta",               label: "Asia/Jakarta  (UTC+7)" },
  { value: "Asia/Kuala_Lumpur",          label: "Asia/Kuala_Lumpur  (UTC+8)" },
  { value: "Asia/Makassar",              label: "Asia/Makassar  (UTC+8)" },
  { value: "Asia/Manila",                label: "Asia/Manila  (UTC+8)" },
  { value: "Asia/Rangoon",               label: "Asia/Rangoon  (UTC+6:30)" },
  { value: "Asia/Seoul",                 label: "Asia/Seoul  (UTC+9)" },
  { value: "Asia/Shanghai",              label: "Asia/Shanghai  (UTC+8)" },
  { value: "Asia/Singapore",             label: "Asia/Singapore  (UTC+8)" },
  { value: "Asia/Taipei",                label: "Asia/Taipei  (UTC+8)" },
  { value: "Asia/Tokyo",                 label: "Asia/Tokyo  (UTC+9)" },
  { value: "Asia/Ulaanbaatar",           label: "Asia/Ulaanbaatar  (UTC+8)" },
  // Europa
  { value: "Europe/Amsterdam",           label: "Europe/Amsterdam  (UTC+1/+2)" },
  { value: "Europe/Athens",              label: "Europe/Athens  (UTC+2/+3)" },
  { value: "Europe/Belgrade",            label: "Europe/Belgrade  (UTC+1/+2)" },
  { value: "Europe/Berlin",              label: "Europe/Berlin  (UTC+1/+2)" },
  { value: "Europe/Brussels",            label: "Europe/Brussels  (UTC+1/+2)" },
  { value: "Europe/Bucharest",           label: "Europe/Bucharest  (UTC+2/+3)" },
  { value: "Europe/Budapest",            label: "Europe/Budapest  (UTC+1/+2)" },
  { value: "Europe/Copenhagen",          label: "Europe/Copenhagen  (UTC+1/+2)" },
  { value: "Europe/Dublin",              label: "Europe/Dublin  (UTC+0/+1)" },
  { value: "Europe/Helsinki",            label: "Europe/Helsinki  (UTC+2/+3)" },
  { value: "Europe/Istanbul",            label: "Europe/Istanbul  (UTC+3)" },
  { value: "Europe/Kiev",                label: "Europe/Kiev  (UTC+2/+3)" },
  { value: "Europe/Lisbon",              label: "Europe/Lisbon  (UTC+0/+1)" },
  { value: "Europe/London",              label: "Europe/London  (UTC+0/+1)" },
  { value: "Europe/Luxembourg",          label: "Europe/Luxembourg  (UTC+1/+2)" },
  { value: "Europe/Madrid",              label: "Europe/Madrid  (UTC+1/+2)" },
  { value: "Europe/Minsk",               label: "Europe/Minsk  (UTC+3)" },
  { value: "Europe/Moscow",              label: "Europe/Moscow  (UTC+3)" },
  { value: "Europe/Oslo",                label: "Europe/Oslo  (UTC+1/+2)" },
  { value: "Europe/Paris",               label: "Europe/Paris  (UTC+1/+2)" },
  { value: "Europe/Prague",              label: "Europe/Prague  (UTC+1/+2)" },
  { value: "Europe/Rome",                label: "Europe/Rome  (UTC+1/+2)" },
  { value: "Europe/Sofia",               label: "Europe/Sofia  (UTC+2/+3)" },
  { value: "Europe/Stockholm",           label: "Europe/Stockholm  (UTC+1/+2)" },
  { value: "Europe/Tallinn",             label: "Europe/Tallinn  (UTC+2/+3)" },
  { value: "Europe/Vienna",              label: "Europe/Vienna  (UTC+1/+2)" },
  { value: "Europe/Warsaw",              label: "Europe/Warsaw  (UTC+1/+2)" },
  { value: "Europe/Zurich",              label: "Europe/Zurich  (UTC+1/+2)" },
  // Pacífico y Oceanía
  { value: "Australia/Adelaide",         label: "Australia/Adelaide  (UTC+9:30/+10:30)" },
  { value: "Australia/Brisbane",         label: "Australia/Brisbane  (UTC+10)" },
  { value: "Australia/Darwin",           label: "Australia/Darwin  (UTC+9:30)" },
  { value: "Australia/Perth",            label: "Australia/Perth  (UTC+8)" },
  { value: "Australia/Sydney",           label: "Australia/Sydney  (UTC+10/+11)" },
  { value: "Pacific/Auckland",           label: "Pacific/Auckland  (UTC+12/+13)" },
  { value: "Pacific/Fiji",               label: "Pacific/Fiji  (UTC+12)" },
  { value: "Pacific/Guam",               label: "Pacific/Guam  (UTC+10)" },
  { value: "Pacific/Honolulu",           label: "Pacific/Honolulu  (UTC-10)" },
  { value: "Pacific/Port_Moresby",       label: "Pacific/Port_Moresby  (UTC+10)" },
  { value: "Pacific/Tongatapu",          label: "Pacific/Tongatapu  (UTC+13)" },
  // UTC
  { value: "UTC",                        label: "UTC  (UTC+0)" },
] as const;
